#!/bin/sh

# Prepare system for OpenVPN.
mkdir -p /dev/net
if [ ! -c /dev/net/tun ]; then
    mknod /dev/net/tun c 10 200
fi

# Database.
pritunl set-mongodb ${DATABASE_URL}

# Network.
pritunl set app.reverse_proxy true
pritunl set app.server_ssl false
pritunl set app.redirect_server false
pritunl set app.server_port ${PORT}

# Start the process.
exec env GODEBUG=netdns=cgo pritunl start